config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'main_pages#home'
  
  get    'about'    => 'main_pages#about'
  get    'help'     => 'main_pages#help'
  get    'login'    => 'sessions#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'
  
  #get route written for ajax call to users controller.
  get 'users/existinguser' => 'users#existinguser', :as => 'existinguser'
  get 'users/existingemail' => 'users#existingemail', :as => 'existingemail'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :recipes
  resources :ingredients
  resources :measurements
  resources :recipe_ingredients,  except: [:show]
  resources :follows,             only:   [:create, :destroy]
  resources :comments,            except: [:show]
  resources :ratings,             except: [:show]
  resources :checklists,          except: [:show]
  resources :checklist_pictures,  except: [:show]
  resources :account_activations, only:   [:edit]
  resources :password_resets,     only:   [:new, :create, :edit, :update]
  
    #If path doesn't match a defined route send traffic to root
  match "*path", to: "main_pages#home", via: :all
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
    #Relationships
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :checklists, dependent: :destroy
  
  #Show recipes in order of user_id and rating
  default_scope -> { order(user_id: :asc, rating: :desc) }
  
  #Add picture uploader
  mount_uploader :picture, PictureUploader
  
  #Recipe names are unique per user
  validates_uniqueness_of :name, scope: :user, on: :create
  
  #Ensure picture is under 5MB
  validate :picture_size
  
#PRIVATE########################################################################
private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/recipes_controller.rb
################################################################################
#Author: Chad Greene
#Date: 12-13-14
#Modifications: 
#Description: The Recipe controller allows users to have a collection of 
#             recipes.
################################################################################
class RecipesController < ApplicationController
    #Allow un-registered users access to all recipes
  skip_before_action :logged_in_user, only: :index
  
    #Ensures owner of object is allowed to edit and delete
  before_action -> { correct_user Recipe.find(params[:id]).user}, 
                   only: [:update, :destroy]
  
  ##############################################################################
  # Builds new user recipe
  #
  # Entry: none
  #
  #  Exit: none
  ##############################################################################
  def new
    @page_title = "New Recipe"
    @recipe = current_user.recipes.build
    @btnText = "Create Recipe"
    @obj = @recipe
    render 'shared/form'
  end
  
  ##############################################################################
  # Saves new recipe for user
  #
  # Entry: dirty form
  #
  #  Exit: form information saved to database
  ##############################################################################
  def create
    @recipe = current_user.recipes.build(recipe_params)
    @btnText = "Create Recipe"
    @obj = @recipe
    if(@recipe.save)
      redirect_to current_user
    else
      flash.now.alert = "Form Error"
      render 'shared/form'
    end
  end
  
  ##############################################################################
  # Removes a user recipe from the database
  #
  # Entry: id is recipe id
  #
  #  Exit: recipe removed from database
  ##############################################################################
  def destroy
    current_user.recipes.find(params[:id]).destroy
    redirect_to current_user
  end
  
  ##############################################################################
  # Allows a user to edit a recipe
  #
  # Entry: none
  #
  #  Exit: none
  ##############################################################################
  def edit
    @page_title = "Edit Recipe"
    @recipe = current_user.recipes.find(params[:id])
    @btnText = "Create Recipe"
    @obj = @recipe
    render 'shared/form'
  end
  
  ##############################################################################
  # Updates a users recipe
  #
  # Entry: id is recipe id
  #        dirty form
  #
  #  Exit: recipe updated with form information
  ##############################################################################
  def update
    @recipe = current_user.recipes.find(params[:id])
    @obj = @recipe
    if(@recipe.update(recipe_params))
      flash.alert = "Recipe updated"
      redirect_to current_user
    else
      flash.now.alert = "Error"
      render 'shared/form'
    end
  end
  
  ##############################################################################
  # Builds list of all recipes
  #
  # Entry: none
  #
  #  Exit: none
  ##############################################################################
  def index
    @page_title = "All Recipes"
    @recipes = Recipe.all
  end
  
  ##############################################################################
  # Displays a single recipe profile
  #
  # Entry: id is recipe_id
  #
  #  Exit: session[:recipe_id] set to recipe id
  ##############################################################################
  def show
    @recipe = Recipe.find(params[:id])
    @page_title = "#{@recipe.name}"
    session[:recipe_id] = @recipe.id
    @rating = @recipe.ratings.find_by(user_id: session[:user_id])
  end
  
#PRIVATE########################################################################  
  private
    ############################################################################
    # Allows only permitted parameters to be submitted and used on the pages
    ############################################################################
    def recipe_params
      params.require(:recipe).permit(:name, :picture)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<!-- Form for editing and new recipes -->
<div class="recipe_entry">
  <!-- Includes multipart for file uploading -->
  <%= form_for(@recipe, html: { multipart: true }) do |f| %>
    <p>
      <!-- Adds name to page hash -->
      <%= f.text_field :name, placeholder: :name %>
    </p>
    <h2>Add Image</h2>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
    <p>
      <!-- Creates/Updates user recipe -->
      <%= f.submit @btnText, class: "myButton" %>
    </p>
  <% end %>
  <script type="text/javascript">
    $('#recipe_picture').bind('change', function() {
      size_in_megabytes = this.files[0].size/1024/1024;
      if(size_in_megabytes > 5) {
        alert('Maximum file size is 5MB.  Please choose a smaller file');
      }
    });
  </script>
</div>

app/views/recipes/_recipe.html.erb
<!--############################################################################
# Displays a single recipe link with average user rating.
#############################################################################-->
<p>
  <%= image_tag recipe.picture.url if recipe.picture? %>
  <%= recipe.user.username %>
  <%= link_to recipe.name, recipe, class: "recipe_entry" %>
  <%= "Average user rating: #{recipe.rating}" if !recipe.rating.nil? %>
</p>
<!-- Show modificaiton links -->
<%= render 'shared/mod_links', object: recipe %>

app/views/recipes/index.html.erb
<% provide(:title, @page_title) %>
<!-- Displays All recipes -->
<%= render @recipes %>
<p>
  <!-- Provide link to add a recipe if user is logged in -->
  <%= link_to 'Add Recipe', new_recipe_path, class: "myButton" if logged_in? %>
</p>

app/views/recipes/show.html.erb
<% provide(:title, @page_title) %>
<!--############################################################################
# Displays information for an individual recipe.  Page contains all recipe
# ingredients, comments, and an overall rating.
#############################################################################-->
<!-- Recipe name as header -->
<h1><%= @recipe.name %></h1>
<h2>Recipe Ingredients</h2>
<!-- Display recipe ingredients in table -->
<div class="ingredients">
  <table>
    <tr>
      <th>Quantity</th>
      <th>Measurement</th>
      <th>Ingredient</th>
      <th>Additional Information</th>
    </tr>
    <%= render @recipe.recipe_ingredients %>
  </table>
    <!-- Provide link to add ingredient if user is owner of recipe -->
    <%= link_to 'Add Ingredient', new_recipe_ingredient_path, 
        class: "myButton" if current_user?(@recipe.user) %>
</div>
<hr />
<h2>Checklist Items</h2>
 <!-- Display all checklist items -->
 <div class="checklists">
  <table>
    <tr>
      <th>Description</th>
      <th>Order</th>
    </tr>
    <%= render @recipe.checklists %>
  </table>
  <%= link_to 'Add Checklist Item', new_checklist_path, 
      class: "myButton" if current_user?(@recipe.user) %>
  
</div>
<hr />
<h2>Comments</h2>
<!-- Display all recipe comments. Newest comments display first -->
<div class="comments">
  <%= render @recipe.comments %>
  <!-- New comment button for logged in users -->
  <%= link_to 'Add Comment', new_comment_path, 
      class: "myButton" if logged_in? %>
</div>
<hr />
<h2>Your Rating</h2>
<!-- Allow logged in users to rate recipe -->
<div class="rating">
  <% if logged_in? %>
    <!-- If user has not rated recipe display add rating button -->
    <% if @rating.nil? %>
      <%= link_to 'Add Rating', new_rating_path, 
          class: "myButton" %>
    <!-- Otherwise show current rating and edit rating button -->
    <% else %>
      <%= "Current rating is: #{@rating.vote}" %>
      <%= link_to 'Edit Rating', edit_rating_path(@rating),
          class: "myButton" %>
    <% end %>
  <% end %>
</div>