config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'main_pages#home'
  
  get    'about'    => 'main_pages#about'
  get    'help'     => 'main_pages#help'
  get    'login'    => 'sessions#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'
  
  #get route written for ajax call to users controller.
  get 'users/existinguser' => 'users#existinguser', :as => 'existinguser'
  get 'users/existingemail' => 'users#existingemail', :as => 'existingemail'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :recipes
  resources :ingredients
  resources :measurements
  resources :recipe_ingredients,  except: [:show]
  resources :follows,             only:   [:create, :destroy]
  resources :comments,            except: [:show]
  resources :ratings,             except: [:show]
  resources :checklists,          except: [:show]
  resources :checklist_pictures,  except: [:show]
  resources :account_activations, only:   [:edit]
  resources :password_resets,     only:   [:new, :create, :edit, :update]
  
    #If path doesn't match a defined route send traffic to root
  match "*path", to: "main_pages#home", via: :all
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
    #Relationships
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/measurements_controller.rb
################################################################################
#Author: Chad Greene
#Date: 12-13-14
#Modifications: 
#Description: The Measurements controller is responsible for measurmemnt objects
#used in the construction of recipe_ingredients
################################################################################
class MeasurementsController < ApplicationController
  
    #Ensures that only admins can add ingredients
  before_action :admin_user
  
  ##############################################################################
  # Allows new measurement to database
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def new
    @page_title = "New Measurement"
    @measurement = Measurement.new
    @btnText = "Add Measurement"
    @obj = @measurement
    render 'shared/form'
  end
  
  ##############################################################################
  # Saves new measurement to database
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def create
    @measurement = Measurement.new(msr_params)
    @obj = @measurement
    if(@measurement.save)
      flash.alert = "Measurement added"
      redirect_to new_measurement_path
    else
      flash.now.alert = "Error adding measurement"
      render 'shared/form'
    end
  end
  
  ##############################################################################
  # Edits an measurement in the database
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def edit
    @page_title = "Edit Measurement"
    @measurement = Measurement.find(params[:id])
    @btnText = "Update Measurement"
    @obj = @measurement
    render 'shared/form'
  end
  
  ##############################################################################
  # Updates an measurement in the database
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def update
    @measurement = Measurement.find(params[:id])
    @obj = @measurement
    if(@measurement.update(msr_params))
      redirect_to @measurement
    else
      render 'shared/form'
    end
  end
  
  ##############################################################################
  # Builds a list of all measurements in database
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def index
    @page_title = "All Measurements"
    @measurements = Measurement.all
  end
  
  ##############################################################################
  # Deletes a measurement from the database.
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def destroy
    @measurement = Measurement.find(params[:id]).destroy
    redirect_to measurements_path
  end
  
  ##############################################################################
  # Shows a measurement from the database.
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def show
    @measurement = Measurement.find(params[:id])
    @page_title = "#{@measurement.name}"
  end
  
#PRIVATE########################################################################
private
  ############################################################################
  # Allows only permitted parameters to be submitted and used on the pages
  ############################################################################  
  def msr_params
    params.require(:measurement).permit(:name, :abbr)
  end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<!-- Form used for both new and editing measurements -->
<%= form_for @measurement do |f| %>
  <p>
    <%= f.text_field :name, placeholder: 'Name' %>
  </p>
  <p>
    <%= f.text_field :abbr, placeholder: 'Abbreviation' %>
  </p>
  <p>
    <%= f.submit @btnText, class: "myButton" %>
  </p>
<% end %>

app/views/measurements/_measurement.html.erb
<!-- Displays a single ingredient -->
<tr class="measurement">
  <td><%= measurement.name %></td>
  <td><%= measurement.abbr %></td>
  <td>
    <%= link_to 'edit', edit_measurement_path(measurement) %>
    <%= link_to 'delete', measurement_path(measurement), method: :delete, 
                          data: { confirm: 'Are you sure?' } %></td>
  </td>
</tr>

app/views/measurements/index.html.erb
<% provide(:title, @page_title) %>
<!--############################################################################
#  An automatic foreach loop is used to process the @measurements instance
#  variable.  The measurements are displayed by calling the show function
#  for each measurement.
#############################################################################-->
<table>
  <tr>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>&nbsp</th>
  </tr>
  <%= render @measurements %>
</table>

app/views/measurements/show.html.erb
<% provide(:title, @page_title) %>
<!-- _measurement.html.erb displays the comment -->
<%= render @measurement %>