config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'main_pages#home'
  
  get    'about'    => 'main_pages#about'
  get    'help'     => 'main_pages#help'
  get    'login'    => 'sessions#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'
  
  #get route written for ajax call to users controller.
  get 'users/existinguser' => 'users#existinguser', :as => 'existinguser'
  get 'users/existingemail' => 'users#existingemail', :as => 'existingemail'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :recipes
  resources :ingredients
  resources :measurements
  resources :recipe_ingredients,  except: [:show]
  resources :follows,             only:   [:create, :destroy]
  resources :comments,            except: [:show]
  resources :ratings,             except: [:show]
  resources :checklists,          except: [:show]
  resources :checklist_pictures,  except: [:show]
  resources :account_activations, only:   [:edit]
  resources :password_resets,     only:   [:new, :create, :edit, :update]
  
    #If path doesn't match a defined route send traffic to root
  match "*path", to: "main_pages#home", via: :all
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  belongs_to :recipe
  has_many :checklist_pictures
end

app/controllers/checklists_controller.rb
################################################################################
#Author: Chad Greene
#Date: 12-13-14
#Modifications: 
#Description: The Checklists controller allows users to post 1 or many 
# checklist items to an individual recipe.
################################################################################
class ChecklistsController < ApplicationController
  
  ##############################################################################
  # Builds a new checklist to store in the database
  #
  # Entry: none
  #
  #  Exit: none
  ##############################################################################
  def new
    @page_title = "New Checklist Item"
    @checklist = current_recipe.checklists.build
    @btnText = "Create Checklist Item"
    @obj = @checklist
    @images = @checklist.checklist_pictures.all
    render 'shared/form'
  end
  
  ##############################################################################
  # Builds a checklist from the allowed page parameters.  If save was successful
  # user is directed back to the recipe they were on otherwise the user is 
  # allowed to fix errors on the checklist page and re-submit
  #
  # Entry: dirty form
  #
  #  Exit: form information saved to database
  ##############################################################################
  def create
    @checklist = current_recipe.checklists.build(checklist_params)
    @obj = @checklist
    if(@checklist.save)
      flash.alert = "Added Checklist Item"
      redirect_back_or current_recipe
    else
      flash.now.alert = "Form Error"
      render 'shared/form'
    end
  end
  
  ##############################################################################
  # Finds a users checklist from the current recipe to display on view.
  #
  # Entry: :verify_user
  #
  #  Exit: none
  ##############################################################################  
  def edit
    @page_title = "Edit Checklist Item"
    @checklist = current_recipe.checklists.find(params[:id])
    @btnText = "Update Checklist Item"
    @obj = @checklist
    @images = @checklist.checklist_pictures.all
    render 'shared/form'
  end

  ##############################################################################
  # Updates checklist with new page parameters
  #
  # Entry: :verify_user
  #
  #  Exit: returns to current_recipe if successful
  #        or allows user to fix errors on the form
  ##############################################################################
  def update
    @checklist = current_recipe.checklists.find(params[:id])
    @obj = @checklist
    if(@checklist.update(checklist_params))
      redirect_back_or current_recipe
    else
      render 'shared/form'
    end
  end
  
  ##############################################################################
  # Deletes a user checklist from the current recipe
  #
  # Entry: :verify_user
  #
  #  Exit: checklist deleted
  ##############################################################################
  def destroy
    current_recipe.checklists.find(params[:id]).destroy
    redirect_back_or current_recipe
  end
  
  ##############################################################################
  # Builds a list of all checklists
  #
  # Entry: :admin_user
  #
  #  Exit: none
  ##############################################################################
  def index
    redirect_to root_url unless admin
    @page_title = "All checklist items"
    @checklists = Checklist.all
  end
  
#PRIVATE########################################################################
  private
    ############################################################################
    # Allows only permitted parameters to be submitted and used on the pages
    ############################################################################
    def checklist_params
      params.require(:checklist).permit(:description, :order, :recipe_id)
    end
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_checklist.html.erb
<% @images = checklist.checklist_pictures.all %>
<!-- Shows information for a single checklist item-->
<tr>
  <!-- Checklist description -->
  <td><%= checklist.description %></td>
  <!-- The comment -->
  <td><%= checklist.order %></td>
  <!-- Show modificaiton links -->
  <td>
    <%= render 'shared/rmod_links', object: checklist %>
  </td>
  <td>
    <% if @images.any? %>
      <% @images.each do |i| %>
        <%= image_tag i.picture.url %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/checklists/_form.html.erb
<!-- Form used for both new and editing checklist items -->
<div class="form">
<%= form_for @checklist do |f| %>
  <p>
    <!-- Adds description to page hash -->
    <%= f.text_area :description, placeholder: 'Item' %>
  </p>
  <p>
    <!-- Adds order to page hash -->
    <%= f.number_field :order, placeholder: 'Order' %>
  </p>
  <% if @images.any? %>
    <p>
      <h2>Current Images</h2>
      <% @images.each do |i| %>
        <%= image_tag i.picture.url %>
      <% end %>
    </p>
  <% end %>
  <% if controller.action_name != 'new' %>
  <p>
    <%= link_to 'Add Image', new_checklist_picture_path(@checklist) %>
  </p>
  <% end %>
  <!-- Creates/Edits checklist item -->
  <p>
    <%= f.submit @btnText, class: "myButton" %>
  </p>
<% end %>
</div>

app/views/checklists/edit.html.erb
<% provide(:title, @page_title) %>
<!-- Displays edits checklist form -->
<%= render 'form' %>

app/views/checklists/index.html.erb
<% provide(:title, @page_title) %>
<!--############################################################################
#  An automatic foreach loop is used to process the @checklists instance
#  variable.  The checklist items are displayed by calling the show function
#  for each checklist item.
#############################################################################-->
<table>
  <tr>
    <th>Description</th>
    <th>Order</th>
  </tr>
  <%= render @checklists %>
</table>

app/views/checklists/new.html.erb
<% provide(:title, @page_title) %>
<!-- Displays new checklist form -->
<%= render 'form' %>